fail_on_severity: critical
deny_packages:
  # particularly eggregious crypto module
  - 'pkg:npm/crypto-js'
  # log4j vulnerable to log4shell
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.17.0'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.16.0'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.15.0'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.14.1'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.14.0'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.13.3'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.13.2'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.13.1'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.13.0'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.12.4'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.12.3'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.12.2'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.12.1'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.12.0'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.11.2'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.11.1'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.11.0'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.10.0'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.9.1'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.9.0'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.8.2'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.8.1'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.8'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.7'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.6.2'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.6.1'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.6'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.5'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.4.1'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.4'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.3.2'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.3.1'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.3'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.2'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.1'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.0.2'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.0.1'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.0-rc2'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.0-rc1'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.0-beta9'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.0-beta8'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.0-beta7'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.0-beta6'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.0-beta5'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.0-beta4'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.0-beta3'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.0-beta2'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.0-beta1'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.0-alpha2'
  - 'pkg:maven/org.apache.logging.log4j/log4j-core@2.0-alpha1'
# Any number of groups (namespaces in purl format) to block in a PR.
deny_groups: 
  - 'pkg:maven/log4j'
warn_only: true
